Copa_Do_Mundo_MVC/Controllers/EmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Copa_Do_Mundo_MVC.Controllers
{
    public class EmailController : Controller
    {

        public EmailController() 
        { 
            WebMail.SmtpServer = "xxxxxxxxx"; 
            WebMail.EnableSsl = true; 
            WebMail.SmtpPort = 587; 
            WebMail.From = "xxxxxx"; 
            WebMail.UserName = "cxxxxxxxxxxx"; 
            WebMail.Password = "xxxx"; 
        } 
        // 23 // POST: /Email/Envia 
        
        [HttpPost] 
        public ActionResult Envia(string mensagem) 
        { 
            WebMail.Send("EMAIL", "Copa do Mundo - Erro", mensagem); 
            return View(); 
        } 


    }
}

Copa_Do_Mundo_MVC/Controllers/ErroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Copa_Do_Mundo_MVC.Controllers
{
    public class ErroController : Controller
    {
        // GET: /Erro/Desconhecido 
        public ActionResult Desconhecido() 
        { 
            return View(); 
        } 

        // 20 // GET: /Erro/PaginaNaoEncontrada 
        public ActionResult PaginaNaoEncontrada() 
        { 
            return View(); 
        } 
    }
}

Copa_Do_Mundo_MVC/Views/Erro/Desconhecido.cshtml
@{ Layout = null;
}
<!DOCTYPE html>

<html>
<head>

    <meta name="viewport" content="width=device-width" />

    <title>Problema no servidor</title>
</head>

    <body>
        <h2>Desculpe , tivemos problema em nosso servidor. Volte dentro de alguns instantes.</h2>

        <p>Envie uma mensagem para os administradores do sistema.</p>
        @using (Html.BeginForm("Envia", "Email"))
        {
            <div class="editor-label">
                @Html.Label("Mensagem")
            </div> <div class="editor-field">
                @Html.TextArea("Mensagem")
            </div> <input type="submit" value="Enviar" />
        }

    </body>
</html>

Copa_Do_Mundo_MVC/Views/Erro/PaginaNaoEncontrada.cshtml
@{ Layout = null;
}
<!DOCTYPE html>

<html>

<head>

    <meta name="viewport" content="width=device-width" />
    <title>Página não encontrada</title>
</head>
<body>
    <h2>Página não encontrada</h2>
</body>
</html>